# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Plan1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Plan1_controller:
  ros__parameters:
    joints:
      - yaw_link
      - p1_link
      - p2_link
      - roll_link
      - minip_link
      - minir_link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity